### ISSUE TITLE
Could Not Get Site

### ISSUE THREAD

**Issue by mrkhdly** [c8r/support#15]
Hello 👋,

* Created a  repo https://github.com/mrkhdly/testing
* Copied @jxnblk [data.json](https://github.com/jxnblk/jxnblk.github.io/blob/master/alt.x0/data.json) file into the master branch named compositor.json
* Created a new site in Compositor for that repo
* Tried to created the site & **Could Not Get Site** error popped up

**[Chrome Dev Tool log](https://github.com/c8r/support/files/883487/app.compositor.io-1490899407913.log.zip)**  
<img width="1280" alt="screen shot 2017-03-30 at 1 44 15 pm" src="https://cloud.githubusercontent.com/assets/9424682/24520959/eb05e0b8-154f-11e7-8758-bd9ed9cfa5c6.png">

**Comment by mrmrs** [comment]
Hey @mrkhdly - so the data.json that is used for http://jxnblk.com is generated with a different engine and not compatible with what generates the sites from GitHub. Sorry for the confusion.
