### ISSUE TITLE
Unsubscribe from Monthly Lab Payment

### ISSUE THREAD

**Issue by benz2012** [c8r/support#23]
I just wanted to try out Lab for 1 month, and now I would like to unsubscribe but I can't seem to find any place on the website or in the app to do so.

**Comment by johno** [comment]
Hey @benz2012, we're in the midst of building out the web dashboard so we've been handling account management over email for the time being. I've cancelled your subscription and refunded you for the current month.

Thanks for trying out Lab!

**Comment by tlvenn** [comment]
Hi @johnotander,

Could you please cancel my subscription as well. Thanks in advance.

**Comment by johno** [comment]
Done @tlvenn. Thanks for taking Lab for a spin!

**Comment by rpdasilva** [comment]
@johno could you please cancel my subscription as well?
Cheers!
