### ISSUE TITLE
Preview url needs trailing slash

### ISSUE THREAD

**Issue by daviddarnes** [c8r/support#3]
Hi, first time using compositor and it's working great so far. Noticed that the preview link that is shown in the app after I hit Publish gives me the following url:

`https://daviddarnes.github.io/compositor-test`

When it actually should be:

`https://daviddarnes.github.io/compositor-test/`

Seems like preview urls just need a trailing `/`. Hope this helps!

**Comment by johno** [comment]
Thanks for reporting. We've just deployed a fix so urls now include the trailing `/`. Please let us know if you encounter any more issues. 👯

**Comment by daviddarnes** [comment]
👌✨
