### ISSUE TITLE
Usage guide needed

### ISSUE THREAD

**Issue by nickbytes** [c8r/support#4]
Do you have a usage guide? Guessing you're hard at work on this – really excited about where it's going! Figuring out as I try different things (i.e. if I edit README content shows) 😬 Would love to help/provide more feedback.

![image](https://cloud.githubusercontent.com/assets/3009331/18177624/a6d0f0fe-7040-11e6-96f8-1b9c5e9c754c.png)

**Comment by jxnblk** [comment]
Hey thanks! We don't currently have a guide, but would love to hear your thoughts on what things were difficult to use or confusing

**Comment by nickbytes** [comment]
This 100% my fault. Had in my mind that this was a sort of jekyll-esque generator, rather than a project page generator. Some of that confusion came from starting with a new repo, rather than defaulting to project already created w/ README. 

Very happy about it though, this is brilliant. Great [stuff](http://nickbytes.com/shrug/).
