### ISSUE TITLE
Cannot create a new site

### ISSUE THREAD

**Issue by GarthDB** [c8r/support#6]
Seems like a different problem than https://github.com/c8r/support/issues/2

When I login it still asks me to login:
![image](https://cloud.githubusercontent.com/assets/125516/18215283/b67549b0-710d-11e6-8329-8242d8dc1feb.png)

When I click create new site it sends me to the subscribe screen:
![image](https://cloud.githubusercontent.com/assets/125516/18215313/d452ee10-710d-11e6-9755-7ea1e29fa2f4.png)

It might have something to do with the fact that my github username is case sensitve (GarthDB).

It's caused other issues in the past. I don't have any ideas past that.

**Comment by johno** [comment]
Thank you for reporting, we just deployed a fix that should resolve your issue when logging in 🎯 . Please let us know if you run into any more issues (or if for some reason this wasn't resolved). Thanks!

**Comment by GarthDB** [comment]
Fixed, thanks.

**Comment by jamesmcallister** [comment]
I'm getting the same.

I sign in and auth guthub, click on my name at the top right "+ New Site". then i get the "https://app.compositor.io/register" page.

Anything i can try?

**Comment by jxnblk** [comment]
@jamesmcallister Hi, I think the username we had listed was capitalized and might not have been letting you in. I've deployed an update which should let you in now. Please let me know if you try and still can't access the app.

**Comment by jamesmcallister** [comment]
@jxnblk yes that's fixed it. thank you.
