### ISSUE TITLE
Markdown TOC and HTML tags support?

### ISSUE THREAD

**Issue by miguelpaz** [c8r/support#8]
I have a Table of Contents in a .md file and in some of the templates the indentation of the TOC elements works and in some it does not.
Example: 
- Assignments and Due Dates
		- Assignment 1
I also have a table using `<table>`, `<tr>`,  `<td>` and the templates don't show the table.

**Comment by mrmrs** [comment]
@miguelpaz Will add this to our roadmap. We definitely have improvements to the markdown parsing to make.

**Comment by miguelpaz** [comment]
Thanks
